version: '3.9'
services:

  base:
    build:
      context: .
      dockerfile: ./infrastructure/docker/Dockerfile

  api:
    extends:
      service: base
    volumes:
        - ./infrastructure/docker/assets:/service/assets
    ports:
      - "3030:3030"
    restart: always